### ISSUE TITLE
Docker certificate will be overwritten after rebooting

### ISSUE THREAD

**Issue by phstudy** [Azure/azure-docker-extension#4] opened 2014-12-19 03:44 UTC
This extension will overwrite certificate in `/etc/docker.io/` after rebooting. It means that user does not have a chance to change docker certificate.

In addition to certificate will be reset, the setting in `/etc/default/docker.io` will also be reset.

**Comment by ahmetalpbalkan** [comment] 2015-04-15 18:59
@phstudy sorry for not getting back on this earlier. opened up #18 to follow up on this.

**Comment by phstudy** [comment] 2015-04-16 06:13
@ahmetalpbalkan I think certificate update should be a normal operation, so I do not want it to be overwritten everytime.
I created Docker VM through azure-cli.

**Comment by ahmetalpbalkan** [comment] 2015-04-16 07:20
@phstudy there's no option to not to upload Docker certs while creating Docker VM through azure-cli, that's by design.

We mostly expect beginner users to use azure-cli for creating Docker VMs and advanced users to use docker-machine or set up the machines themselves with docker manually, which is where you can get the fine tuning.

I'm still trying to understand your use case. So when you create a VM with Docker extension through azure-cli, your Docker certs are already uploaded to VM's `/etc/docker/*`.

1. Do you change those certificates manually after that?
2. What do you mean by "extension will overwrite certificate in /etc/docker"? Did you already place them there in advance somehow?
3. What operation exactly causes certificates you have at /etc/docker to be overwritten?

**Comment by phstudy** [comment] 2015-04-16 07:55
@ahmetalpbalkan 
At first, I create Docker VM with default certificate which was created by azure-cli, and I found it didn't fulfill my requirement. So I replace the default certificate with my certificate.

1. Yes, I update certificate through ansible script after VM creation.
2. No, I put my certificate in `/etc/docker` after VM creation.
3. Reboot Azure VM

**Comment by ahmetalpbalkan** [comment] 2015-04-16 16:47
Ah I see. It's happening because `enable` step we have copies the certs instead of only starting docker. I suppose we should move this to `install` step. Thanks for reporting we'll follow up on our side.

**Comment by ahmetalpbalkan** [comment] 2015-06-05 20:14
Hi @phstudy,

We just published a brand new Docker Extension (not available via CLI yet, user guide on how to deploy the new one is in the README). This should be solving your problem (i.e. not overwriting certs) and we introduced new options in the extension configuration file to configure your docker engine, if needed. 

Closing this issue now, let us know if the new solution does not solve your problem.

**Closed by ahmetalpbalkan** 2015-06-05 20:14 UTC
