### ISSUE TITLE
Malformed Compose Templates Hang

### ISSUE THREAD

**Issue by gabrielhartmann** [Azure/azure-docker-extension#32] opened 2015-06-08 16:39 UTC
Malformed compose templates currently hang deployment of the extension.  It should fail instead.

**Comment by ahmetalpbalkan** [comment] 2015-06-08 16:44
Hmm can u pls send the logs and the /var/lib/waagent/ExtensionName/status/ files

**Comment by gabrielhartmann** [comment] 2015-06-08 17:22
https://gist.github.com/gabrielhartmann/7524544b917f87f7de8d

Logs indicate success.  I'm pretty sure I saw this hung in the portal though.  Might have to repro.  In any case, malformed config should probably result in failure, not success.

**Comment by ahmetalpbalkan** [comment] 2015-06-08 17:24
What is the malformed config you specified?

**Comment by gabrielhartmann** [comment] 2015-06-08 17:26
https://gist.github.com/gabrielhartmann/a1d9d2842a84d79d400b

I believe the only error is that I used "composeup" instead of "compose".  I could be wrong.  Still trying to get my template working with the new extension.

**Comment by ahmetalpbalkan** [comment] 2015-06-08 17:32
I think I'm gonna call this "by design". That's not malformed config. it's just you have an extraneous key.

 We don't do strict validation of the object (simply because it's json anyway). If you were specifying a string for "compose" field, that would certainly be a bad input. 

I guess we could do strict checking in theory, but I'm not sure if it's worth it to implement ( golang's json serializer can't do that either so we have to write our own unmarshaler in that case).

I am hoping to help people diagnose their problems in this repo and I expect them to read the user guide. If we happen to receive considerable amount of feedback about getting the config right, we might do something, otherwise that's a wontfix for now.

**Comment by gabrielhartmann** [comment] 2015-06-08 17:35
Ok.  If you want I can open a new issue.  But I just deployed with a correct config.  Redis container is running, but the deployment still hangs forever.  Extensions are listed as Created, but not "OK".  Command line is hung too.

**Comment by ahmetalpbalkan** [comment] 2015-06-08 17:36
Can you send the status / log file again please? Does the 1.status indicate success?

**Comment by gabrielhartmann** [comment] 2015-06-08 17:37
![image](https://cloud.githubusercontent.com/assets/567111/8041058/43519daa-0dca-11e5-83d2-5e085cb24028.png)

![image](https://cloud.githubusercontent.com/assets/567111/8041062/51fb9126-0dca-11e5-9903-9fff5c0f7c80.png)

**Comment by ahmetalpbalkan** [comment] 2015-06-08 17:40
Yeah I got that part. If the extension is reporting status as success but the cli/portal is hanging, it's a LiveSite issue; not docker extension.

**Comment by gabrielhartmann** [comment] 2015-06-08 17:41
https://gist.github.com/gabrielhartmann/1e94a30ecf6097d3c1f0

**Comment by ahmetalpbalkan** [comment] 2015-06-08 17:51
Yep waagent.log is indicating success about enable too. Closing as we're following up internally.

**Closed by ahmetalpbalkan** 2015-06-08 17:51 UTC
Labels: low-priority, question
